Added a fix for the checksum of sha256sum
sundowndev/phoneinfoga pull request #1006
Opened 2022-02-18 11:42 UTC by pmburu

2022-02-19 07:18 UTC, sundowndev requested changes
Thank you for this fix 🎉 

Just left a small comment to override any existing occurrence of `PhoneInfoga`.

2022-02-20 00:43 UTC, pmburu commented on support/scripts/install
> +  echo "$(curl -sSL https://github.com/sundowndev/phoneinfoga/releases/download/$phoneinfoga_version/PhoneInfoga_checksums.txt) phoneinfoga_$os.tar.gz" | sha256sum --strict --check --ignore-missing
If we touch the txt file name on the script, we have to rename it on the release as well. Would you like me to rename it?

2022-02-22 06:32 UTC, sundowndev commented on support/scripts/install
> +  echo "$(curl -sSL https://github.com/sundowndev/phoneinfoga/releases/download/$phoneinfoga_version/PhoneInfoga_checksums.txt) phoneinfoga_$os.tar.gz" | sha256sum --strict --check --ignore-missing
It's already in lowercase in the release, isn't it ? https://github.com/sundowndev/phoneinfoga/releases

2022-03-01 15:44 UTC, pmburu commented on support/scripts/install
> +  echo "$(curl -sSL https://github.com/sundowndev/phoneinfoga/releases/download/$phoneinfoga_version/PhoneInfoga_checksums.txt) phoneinfoga_$os.tar.gz" | sha256sum --strict --check --ignore-missing
Hi @sundowndev, did you need me to do anything else to the project? Thanks

2022-03-03 06:24 UTC, sundowndev commented on support/scripts/install
> +  echo "$(curl -sSL https://github.com/sundowndev/phoneinfoga/releases/download/$phoneinfoga_version/PhoneInfoga_checksums.txt) phoneinfoga_$os.tar.gz" | sha256sum --strict --check --ignore-missing
Yes, please use `phoneinfoga_checksums` here

2022-03-03 11:38 UTC, pmburu reviewed
Hello @sundowndev , I made the changes. Please have a look at it and let me know whether it is okay.

2022-03-03 11:41 UTC, pmburu commented on support/scripts/install
> +  echo "$(curl -sSL https://github.com/sundowndev/phoneinfoga/releases/download/$phoneinfoga_version/PhoneInfoga_checksums.txt) phoneinfoga_$os.tar.gz" | sha256sum --strict --check --ignore-missing
@sundowndev, it is done now. Please have a look at it and let me know whether it is aligned thanks.

2022-03-03 12:05 UTC, sundowndev approved these changes
Thank you 🙏🏻 ❤️

2022-03-03 12:18 UTC, merged