Update the request for numverify scan
sundowndev/phoneinfoga pull request #1072
Opened 2022-06-11 14:04 UTC by kriss-u

Previously, the API endpoint to perform a numverify scan was as follows.
```javascript
GET https://apilayer.net/api/validate?access_key=access_key&number=phone_number
```

This has been changed to the following.
```javascript
GET https://api.apilayer.com/number_verification/validate?number=phone_number
apikey: access_key
```
I still don't know why the previous endpoint gets a hit and returns a response but doesn't do the verification job. The following is the screenshot after making the change. No automation tests are run.

![image](https://user-images.githubusercontent.com/24423580/173191170-5f00ba33-83e5-4199-a0b7-9a551ca6e243.png)

2022-06-14 06:54 UTC, sundowndev requested changes
Thank you for taking the time to fix this 🙏🏻 

You just need to fix tests now, feel free to ask if you need help on that.

2022-06-16 07:59 UTC, kriss-u commented
@sundowndev I updated the tests to match the new URLs. However, the tests are failing, maybe because of the API keys. Can you please pull this branch and check what needs to be done.

2022-06-19 09:07 UTC, sundowndev commented
Hey @kriss-u I took a look and it seems that the Go http lib transforms the header key to camel case, so the `apikey` header key becomes `Apikey`. Change this in the tests and it should be ok : `MatchHeader("Apikey", "...")`

2022-06-19 10:18 UTC, kriss-u commented
@sundowndev It should work now. I had also forgotten to change the server test to mock the response. The tests didn't fail afterwards. Thanks for the help!

2022-06-19 19:32 UTC, sundowndev approved these changes
Thank you for spending time on this 🙏🏻  ❤️

2022-06-19 19:32 UTC, merged