Add error to printed message when plugin fails to open
sundowndev/phoneinfoga pull request #1196
Opened 2023-01-17 19:52 UTC by bdoner

When a plugin fails to open, print the error from the open call to aid in debugging why your custom scanner wont work.

2023-01-18 07:44 UTC, sundowndev requested changes
Thanks for your PR 👍🏻 

Could you edit tests as well? Look at `scanner_test.go`.

2023-01-20 10:03 UTC, bdoner commented
> Thanks for your PR 👍🏻
> 
> Could you edit tests as well? Look at `scanner_test.go`.

I've updated the test to reflect the expected output.

2023-01-22 09:55 UTC, sundowndev approved these changes

2023-01-22 09:55 UTC, merged

2023-01-22 10:31 UTC, sundowndev commented
Released in [v2.10.2](https://github.com/sundowndev/phoneinfoga/releases/tag/v2.10.2)

2023-07-02 13:23 UTC, Denska10 commented
Error