Added number.Local in combination with facebook searches
sundowndev/phoneinfoga pull request #728
Opened 2021-03-15 14:34 UTC by thehandsomezebra

Facebook Pages (businesses, etc) in the US will not return any results with `RawLocal` formatting -- it requires `(000) 000-0000` Local formatting to get best results.

2021-03-15 17:14 UTC, sundowndev commented
Hi, thanks for this PR!

Could you please update the tests as well ?

2021-03-15 19:05 UTC, thehandsomezebra commented
> Hi, thanks for this PR!
> 
> Could you please update the tests as well ?

I think this should do it:
https://github.com/sundowndev/PhoneInfoga/pull/728/commits/f81430741e2e2100c826fd3a24b1c8906174af91

2021-03-18 10:12 UTC, ankitk2601 approved these changes

2021-04-09 13:28 UTC, sundowndev requested changes
Unit tests still need to be fixed

2021-04-09 13:28 UTC, sundowndev commented on scanners/google_test.go
> +					Dork:   "site:facebook.com intext:\"33673421322\" OR intext:\"+33673421322\"  OR intext:\"06 73 42 13 22\" OR intext:\"0673421322\"",
There's a typo in your patch, you added an extra space before `OR intext:\"06 73 42 13 22\"`

2021-04-09 15:28 UTC, thehandsomezebra commented
My apologies, I'm not well-versed in go and I'm having some difficulties with something so simple.  I will give it another attempt this weekend.

2021-04-09 15:40 UTC, sundowndev commented
> My apologies, I'm not well-versed in go and I'm having some difficulties with something so simple. I will give it another attempt this weekend.

No problem, thank you for checking out anyway, I'll dig into this when I have some free time.

2023-02-13 08:58 UTC, sundowndev commented
Closing for inactivity. Feel free to reopen and fix the PR.

2023-02-13 08:58 UTC, closed without merging